name: Build and Push Docker Image

# Se ejecuta cuando hay un push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código del repositorio
    - name: Check out the repository
      uses: actions/checkout@v4

    # Paso 2: Iniciar sesión en Docker Hub utilizando las credenciales guardadas en los secrets
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Paso 3: Construir la imagen Docker utilizando el Dockerfile
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/clases_udem:latest .

    # Paso 4: Etiquetar la imagen Docker con el hash del commit actual
    - name: Tag Docker image with commit hash
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/clases_udem:latest ${{ secrets.DOCKER_USERNAME }}/clases_udem:${{ github.sha }}

    # Paso 5: Subir la imagen etiquetada a Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/clases_udem:${{ github.sha }}

    # (Opcional) Subir la imagen etiquetada como "latest"
    - name: Push Docker image with latest tag
      run: docker push ${{ secrets.DOCKER_USERNAME }}/clases_udem:latest
